services:
    - docker

sudo: required

before_install:
    - cp .env.dusk.local .env
    - docker-compose build
    - docker-compose up -d
    - docker exec -it richwholesale.local composer install --no-interaction
    - docker exec -it richwholesale.local php artisan migrate --seed
    - npm install
    - npm run production


script:
    - docker exec -it richwholesale.local vendor/bin/phpunit

notifications:
    email: false
