language: php

php:
    - 7.2

dist: trusty

sudo: required

services:
    - docker

before_install:
    - sudo /etc/init.d/mysql stop
    - cp .env.travis .env
    - docker-compose build
    - docker-compose up -d
    - docker ps -a

install:
    - docker exec -it richwholesale.local composer install --no-interaction
    - docker exec -it richwholesale.local php artisan migrate:fresh --seed
    - docker exec -it richwholesale.local npm install
    - docker exec -it richwholesale.local npm run production

script:
    - docker exec -it richwholesale.local vendor/bin/phpunit

notifications:
    email: false
