version: '3'
services:
    php-fpm:
        container_name: richwholesale
        build:
            context: ./docker/php-fpm
        volumes:
            - ./:/var/www:cached
            - ~/.ssh:/root/.ssh:cached
        networks:
            - default
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/logs:/var/log
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
        networks:
            - default
networks:
    default:
        external:
            name: melbrother_network
