version: '3'
services:
    web:
        build:
            context: ./docker
        container_name: richwholesale
        ports:
            - 8080:80
        volumes:
            - ./:/var/www:cached
            - ~/.ssh:/root/.ssh:cached
            - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
        environment:
            DB_HOST: mysql
        networks:
            - default
networks:
    default:
        external:
            name: melbrother_network
